packageExtensions:
  '@ant-design/icons@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@babel/parser@*':
    dependencies:
      '@babel/types': 7.8.3
  cz-lerna-changelog@*:
    peerDependencies:
      semantic-release: '*'
  rc-animate@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-collapse@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-dialog@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-drawer@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-field-form@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-input-number@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-mentions@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-menu@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-notification@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-rate@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-slider@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-tabs@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  react-final-form@*:
    peerDependencies:
      typescript: '*'
  ts-jest@*:
    dependencies:
      jest-config: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-rc.js
